### ISSUE TITLE
error 2019 missed lib in editor mode

### ISSUE THREAD

**Issue by vttry** [getnamo/socketio-client-ue4#80] opened 2018-05-29 12:48 UTC
Hello i have an issue, i can't compile application in ue4 editor i use (SocketIO 0.6.4 and ue version - 4.17 )

`error LNK2019: __declspec(dllimport) public: static class FString __cdecl USIOJConvert::ToJsonString(class TSharedPtr<class FJsonValue,0> const &)...`

It looks like some libs are missed but in debug game are workings fine. What can might be wrong?
In my build cs files i have SocketIOClient 
`PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore", "Json", "JsonUtilities","SocketIOClient" });`
thank you for any help

**Comment by vttry** [comment] 2018-06-01 13:33
Hello getnamo,
Thank you for your answer. I added this dependency module to build.cs. It was still doesen't compile for DebugGameEditor only for DebugGame. But error was change 
` LNK2001  ""public: __cdecl FSocketIONative::FSocketIONative(void)" (??0FSocketIONative@@QEAA@XZ)" Rasunda_NeoX `
I dont know the main. Why does it compile in DebugGame and doesen't compile in DebugGameEditor

**Comment by getnamo** [comment] 2018-06-11 15:25
You'll need to provide a code example of what's failing to compile. Have you tried the latest build of the plugin and see if it also has the same issue? If it does, could you make a minimal project that reproduces this problem?

**Comment by vttry** [comment] 2018-06-12 15:49
Hello getnamo, 
thank you for yor ansver.
I use ue 4.17. Max version of socketio-client-ue4 which works wit this ue is 7.00. If I compile gameEditor build - all works fine,but if compile debugeditor - i have errors (see above)
I made minimal project from ue template. I only add custom playercontroller class and only one metod inside mycontroller.cpp init() there is a code:
`//mycontroller.h
#include "SocketIOClientComponent.h"
#include "SocketIONative.h"
#include "RemoteController.generated.h"

UCLASS()
class TESTPROJECT_API ARemoteController : public APlayerController
{
	GENERATED_BODY()
};

`
`//mycontroller.cpp
#include "RemoteController.h"

void init()
{
	FSocketIONative* NativeClient = new FSocketIONative;
	NativeClient->Connect(FString("http://127.0.0.1:3000"), nullptr, nullptr);
	NativeClient->OnEvent(
		FString("chat message"),
		[&](const FString& Event, const TSharedPtr<FJsonValue>& Message) {
	});
}

`
`
//projectBuild.css
using UnrealBuildTool;

public class TestProject : ModuleRules
{
	public TestProject(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
	
		PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore", "SocketIOClient",  "json"});

		PrivateDependencyModuleNames.AddRange(new string[] {  });
	}
}

`
There is a zip file with project. But if you want to compile it you have to comment metod init(), becase in editor buid mode it doesent work only in debug game. [https://drive.google.com/open?id=11uzo0rh1wT1F8qT7DuKW0GpVuL3WlkUh]

**Comment by getnamo** [comment] 2019-02-15 21:21
SIOJson is likely missing in public PublicDependencyModuleNames. Closing due to plugin age in question, update to newer and check if issue persists.

**Closed by getnamo** 2019-02-15 21:21 UTC
Labels: Awaiting Replication, question
