### ISSUE TITLE
Connection problem but no connection or disconnection (https issue)

### ISSUE THREAD

**Issue by Fobrales** [getnamo/socketio-client-ue4#146] opened 2019-08-24 13:19 UTC
Hello!
I can't connect socket.io server. Event ConnectionProblem is happened, but Event Connected or Disconnected isn't (that's why I can't to find reason of disconnection). 
http://prntscr.com/ow3b5j - actor blueprint
http://prntscr.com/owxqh4 - properties of SocketIOClient
http://prntscr.com/owxqz5 - log
Win64.
I try to connect in 4.19 and 4.22 UE, in only blueprint project and C++ project. Also I downloaded your example project. Fail too..
Thanks for help.

**Comment by getnamo** [comment] 2019-08-25 03:41
possible duplicate of https://github.com/getnamo/socketio-client-ue4/issues/126. Currently recommend rolling back to v0.10 until solution is found. Seems to occur if server disconnects and reconnects it loses the 'pong' timeout reset and causes the connection to reset.

**Comment by Fobrales** [comment] 2019-08-25 23:03
I try to connect in UE 4.21 and 4.22 with plugin v0.10, but I got the same result ConnectionProblems.
Hmm.. At 126, the client connects to the server and then disconnects, but in my case, the connection doesn't occur. Also there are no messages in the console.log that client connected or disconnected. 
Maybe I need to do something with the server? Thanks for any advice.

**Comment by getnamo** [comment] 2019-09-25 23:51
based on 2nd screenshot, this is a duplicate of https://github.com/getnamo/socketio-client-ue4/issues/39

**Closed by getnamo** 2019-09-25 23:51 UTC
Labels: duplicate
