### ISSUE TITLE
Plugin not visible on macOs High Sierra 10.13.6 - UE 4.20.3

### ISSUE THREAD

**Issue by demanzonderjas** [getnamo/socketio-client-ue4#101] opened 2018-10-15 14:53 UTC
I have installed the Plugin at the project root, and it is enabled in the Plugins-section. I have also rebooted it multiple times, but  it doesn't show up in the Add Component section of my Actor.

Hope this bug can be reproduced and fixed.

**Comment by getnamo** [comment] 2018-10-16 06:31
Duplicate of https://github.com/getnamo/socketio-client-ue4/issues/15.

Mac OS isn't supported atm, we're missing the socket.io and boost static libs compiled for the platform. Not a platform I use so contributions welcome.

**Closed by getnamo** 2018-10-16 06:31 UTC
