### ISSUE TITLE
Crash when quit game (without editor)

### ISSUE THREAD

**Issue by vermicelli** [getnamo/socketio-client-ue4#81] opened 2018-06-08 05:16 UTC
1. Add an actor with the SocketIO component to any level. (Any game, I tried this in the 2D Side Scroller Demo)
2. Cook the game and run it in DebugGame mode.
3. Enter 'quit' command in the game console, you should see a break point is triggered in some engine codes(MallocBinned2.cpp in my case).

Engine version: 4.19.2

**Comment by getnamo** [comment] 2018-06-11 15:15
I've been able to reproduce this issue, thanks for catching it! It appears that when the game runs in monolothic mode (packaged game, development, or debuggame), the thread that sync closes connections invalidated it's own pointer by the time it returned from closing. In order to maintain the current disconnect performance, I re-arranged the removal.

Update has been issued here: https://github.com/getnamo/socketio-client-ue4/commit/c070826c205a9022d025bbf45419397a694e6d32, waiting for some other issues before making a new release.

**Comment by vermicelli** [comment] 2018-06-13 13:40
I'm using the SocketIONative in my GameInstance right now. This problem is still there. I just get a TSharedPtr of FSocketIONative in the Init function of my GameInstance as follows:
`void UGolfGameInstanceBase::Init()
{
  Super::Init();
  SocketIOClient = ISocketIOClientModule::Get().NewValidNativePointer();
}`
When I quit the game, it will crash in some engine code.

If I comment out all codes related to the FLambdaRunnable in the ReleaseNativePointer function, this problem goes away.
So I'm wondering what's the purpose of FLambdaRunnable in this case?

**Comment by getnamo** [comment] 2018-06-13 21:12
Just checking: this is using the released v0.8.3?

If so do you balance your init with e.g. on uninit ```ISocketIOClientModule::Get().ReleaseNativePointer(SocketIOClient);``` ?

see example usage: https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Private/SocketIOClientComponent.cpp#L73

The reason the function uses a FLambdaRunnable to release the pointer is that the act of destroying a socketio connection takes ~ 1 second to complete, so it needs to be backgrounded in order to work in parallel or you will have to wait quite a while to release potentially a many connections use case (I've tested with ~ 1000 on a single client).

**Comment by vermicelli** [comment] 2018-06-14 02:16
Yes, I used the latest release and I called the ReleaseNativePointer in GameInstanc::Shutdown().
![image](https://user-images.githubusercontent.com/8543293/41387877-e9f1dfca-6fbb-11e8-83b0-4f245fb9be4f.png)

![image](https://user-images.githubusercontent.com/8543293/41387861-ce8c6ef8-6fbb-11e8-90bc-f16a5a0e7c70.png)

Call stack when crash shown as follows:
![image](https://user-images.githubusercontent.com/8543293/41387696-e1483244-6fba-11e8-9f16-4467da960fb6.png)

**Comment by vermicelli** [comment] 2018-06-14 10:56
I'm wondering if creating thread in the constructor of FLambdaRunnable cause this problem. Because if I command out the thread creation code and get the FLambdaRunnable object returned from `FLambdaRunnable::RunLambdaOnBackGroundThread` in `FSocketIOClientModule::ReleaseNativePointer` , then call the create function, the game won't crash on quit.
![image](https://user-images.githubusercontent.com/8543293/41408239-92b49fa6-7004-11e8-8ef8-a3447646c621.png)

BTW, I found that you check `if (Thread == NULL)` before delete it in `FLambdaRunnable::~FLambdaRunnable()`. I think what you want here is `!=` or no `if ` at all. Delete a NULL pointer won't cause any problem anyway.

**Comment by getnamo** [comment] 2018-06-14 12:39
Pull the latest change (0.8.4) https://github.com/getnamo/socketio-client-ue4/commit/1825eedc74d108efaf404250fa8e91d17c3adaf8 and let me know if this resolves things. It was long overdue to get rid of my custom lambda code, it's now fully wrapped around Async, this should get rid of some wonky old behavior.

That said I suspect your issue might've been calling ```Disconnect``` before ```ISocketIOClientModule::Get().ReleaseNativePointer(SocketIOClient);```. Releasing the native pointer will guarantee a disconnection anyway, so you can remove it. But if you try an asynchronous disconnect just before the game quits, it may lead to the hang you're experiencing.

I tried making my own game instance like yours in a packaged game, it was all working though and I couldn't replicate the hang/crash in the new system.

**Comment by Wadimich** [comment] 2018-06-14 12:51
Updated, now it's working, no errors on quit or opening level

**Comment by vermicelli** [comment] 2018-06-14 18:09
Thanks for the update! I'll try it later.
This problem isn't caused by `Disconnect` because I built a blank project to test the plugin alone. In that project I just new a pointer in `GameInstance::Init` and release it in `GameInstance::Shutdown` without doing anything else. It still crash when quit.

**Closed** 2018-09-10 16:17 UTC
Labels: addressed awaiting release, bug
