### ISSUE TITLE
Socketio-client-ue4 does not work with Socket.io 3.4.1 in Node.js

### ISSUE THREAD

**Issue by Bioblaze** [getnamo/socketio-client-ue4#253] opened 2021-01-23 21:44 UTC
Just reporting, that the Current Socket.io Client for UE4, does not work with the most current version of Socket.io

**Comment by getnamo** [comment] 2021-01-24 20:07
duplicate of https://github.com/getnamo/socketio-client-ue4/issues/245, there is a plan to upgrade it soonish (tm). Post any questions in that thread.

**Closed by getnamo** 2021-01-24 20:07 UTC
Labels: duplicate
