### ISSUE TITLE
When this plugin can support android?

### ISSUE THREAD

**Issue by xiaoheitwo** [getnamo/socketio-client-ue4#37] opened 2017-04-02 16:06 UTC
hi,
Can you tell me when you plan to add android suport?I have used this plugin for my game,I test my project in win64,it works well,but i package my project to android apk,the plugin doesn't work.I have looked #21 ,but i can't compile it by myself.
Do you have time,can you help me solve it?
 This plugin is really usefull,hope you can help me.

**Comment by getnamo** [comment] 2017-04-03 12:59
Duplicate of https://github.com/getnamo/socketio-client-ue4/issues/21. Android is not my primary platform, so it will require someone else to contribute a solution. It's a matter of recompiling the static libraries (boost and socket.io-cpp) for android, everything else is in theory ready. 

Consider contributing or finding someone who has knowledge of compiling boost for android.

**Closed by getnamo** 2017-04-03 12:59 UTC

**Comment by xiaoheitwo** [comment] 2017-04-07 22:47
ok,I will try it,thanks.
