### ISSUE TITLE
MacOS. Empty URL on Process Url node

### ISSUE THREAD

**Issue by Wadimich** [getnamo/socketio-client-ue4#176] opened 2019-12-03 13:26 UTC
I am working on adaptation my project to MacOS.
After update to UE 4.23.1 i can't do requests, because they are processed with empty URL.

I've did a print string right before Process Url BP node and url exist and right, but the request is failed with empty url

Log file does not have anything valuable and i am not sure, where it breaks.

Reproduce steps:

1. Do get request with Call URL node.
2. Then do second request with Process URL.

By the way, when i am doing Call URL, it works as intented.

**Comment by getnamo** [comment] 2019-12-03 19:42
It looks like Call URL does a ProcessURL internally https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SIOJson/Private/SIOJLibrary.cpp#L233, it's possible you may need to rebuild the request via Construct Json Request for a second process call (https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SIOJson/Private/SIOJRequestJSON.cpp#L225)

**Comment by Wadimich** [comment] 2019-12-03 21:16
For every process call i always construct new json request.

This thing works in Blueprint UObject, there is only Process Request exist.

I have a lot of code, so i would want to not rewrite it using actors or something else

**Comment by getnamo** [comment] 2019-12-05 22:03
You may need to re-write a non-latent variant of applyurl so it can be called in UObject context. It's the latent part that is blocking it from being used in non-graph contexts.

**Comment by Wadimich** [comment] 2019-12-08 23:32
I've resolved my issue. While performing a lot of tests, i've tried to change request url, and, it worked.

So the problem is that failed request contains JSON in url for query parameters. I've deleted it and it works like a charm.

Is that on your side, or engine bug?

**Comment by getnamo** [comment] 2019-12-09 00:12
Interesting, the plugin or the server should definitely warn if a request is invalid due to wrong format. Did your requests reply with error code or did they get dropped silently?

**Comment by Wadimich** [comment] 2019-12-09 04:52
No, they are dropped, get request status returns failed and the code is -1

**Comment by getnamo** [comment] 2020-02-03 18:19
With those status codes it appears to be working as intended. Closing, re-open if there is a better UX suggestion.

**Closed by getnamo** 2020-02-03 18:19 UTC
Labels: enhancement, question
