### ISSUE TITLE
OnFail is not called when no SocketIO Server is running on Address

### ISSUE THREAD

**Issue by LordNed** [getnamo/socketio-client-ue4#50] opened 2017-06-26 18:03 UTC
Unreal 4.16.1 on Windows.

Using the following GameMode setup (copy text from gist, paste into a blank GameMode, ensure BeginPlay is hooked up and create a SocketIOClient variable and hook it up), when trying to connect to a port where the SocketIO server is not running, the OnFail and OnDisconnect messages are not called, so I can't know when it has failed to connect.

https://gist.github.com/LordNed/ace0d2492ae1e18b532536db98b41e1e

Even if you use an entirely invalid address like "fou5k3" none of these callbacks are called.

**Comment by getnamo** [comment] 2017-11-11 07:53
Fixed in https://github.com/getnamo/socketio-client-ue4/commit/f17df08192bdebbae0b0cdabe96fe645e27bccc7.

New plugin architecture has ```OnConnectionProblem``` callbacks which get called whenever the connection severs but the client is attempting to reconnect. By default socket.io clients generally try to reconnect an infinite number of times, but you now have control per component on how often it should retry and how long it should wait in between attempts too. If you run out of reconnection attempts you should get your disconnect calls.

**Comment by getnamo** [comment] 2017-11-11 07:54
Try it out and let me know if this new setup works as intended.

**Closed** 2017-11-16 13:08 UTC
Labels: help wanted
